/api/v1/render:
  post:
    tags:
      - Render
    security: []
    description: Render using markup extension and content
    requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                markup:
                  type: string
                  example: 'mediawiki'
                  required: true
                content:
                  type: string
                  example: '===My wiki title==='
                  required: true
    produces:
      - text/html
    responses:
      200:
        description: Success